<div align="center">
      <h3> <img src="https://github.com/ahammadmejbah/ahammadmejbah/blob/main/Software%20Intelligence%20longo.png?raw=true" width=""></h3>
      <center> <h2><a href="https://github.com/ahammadmejbah/The-90-Day-PyTorch-Mastery-Roadmap/tree/main/Chapter%2001%3A%20Introduction%20to%20PyTorch/Day%201%3A%20Introduction%20to%20Deep%20Learning%20and%20PyTorch"> Full Documentation Link: 👨🏻‍🎓 Day 03: Tensor Operations</a></h2>
     </div>



<body>
<p align="center">
  <a href="mailto:ahammadmejbah@gmail.com"><img src="https://img.shields.io/badge/Email-ahammadmejbah%40gmail.com-blue?style=flat-square&logo=gmail"></a>
  <a href="https://github.com/ahammadmejbah"><img src="https://img.shields.io/badge/GitHub-%40ahammadmejbah-lightgrey?style=flat-square&logo=github"></a>
  <a href="https://linkedin.com/in/ahammadmejbah"><img src="https://img.shields.io/badge/LinkedIn-Mejbah%20Ahammad-blue?style=flat-square&logo=linkedin"></a>
  <a href="https://softwareintelligence.ai/"><img src="https://img.shields.io/badge/Website-Bytes%20of%20Intelligence-lightgrey?style=flat-square&logo=google-chrome"></a>
  <a href="https://www.youtube.com/@IntelligenceAcademy"><img src="https://img.shields.io/badge/YouTube-IntelligenceAcademy-red?style=flat-square&logo=youtube"></a>
  <a href="https://www.researchgate.net/profile/Mejbah-Ahammad-2"><img src="https://img.shields.io/badge/ResearchGate-Mejbah%20Ahammad-blue?style=flat-square&logo=researchgate"></a>
  <br>
  <img src="https://img.shields.io/badge/Phone-%2B8801874603631-green?style=flat-square&logo=whatsapp">
  <a href="https://www.hackerrank.com/profile/ahammadmejbah"><img src="https://img.shields.io/badge/Hackerrank-ahammadmejbah-green?style=flat-square&logo=hackerrank"></a>
</p>


Welcome to **Day 3** of your 90-Day PyTorch Mastery Plan! Today, we will dive deep into **Tensor Operations**, the fundamental building blocks for performing computations in PyTorch. Mastering tensor operations is crucial as they form the basis of all computations in neural networks, from simple arithmetic to complex matrix manipulations.

---

## 📑 **Table of Contents**
1. [Topics Overview](#1-topics-overview)
2. [Basic Tensor Operations](#2-basic-tensor-operations)
    - [2.1. Addition](#21-addition)
    - [2.2. Subtraction](#22-subtraction)
    - [2.3. Multiplication](#23-multiplication)
    - [2.4. Division](#24-division)
3. [In-Place vs. Out-of-Place Operations](#3-in-place-vs-out-of-place-operations)
    - [3.1. Out-of-Place Operations](#31-out-of-place-operations)
    - [3.2. In-Place Operations](#32-in-place-operations)
    - [3.3. When to Use Which](#33-when-to-use-which)
4. [Practical Activities](#4-practical-activities)
    - [4.1. Experimenting with Basic Operations](#41-experimenting-with-basic-operations)
    - [4.2. Understanding In-Place Operations](#42-understanding-in-place-operations)
    - [4.3. Combining Operations](#43-combining-operations)
5. [Resources](#5-resources)
6. [Learning Objectives](#6-learning-objectives)
7. [Expected Outcomes](#7-expected-outcomes)
8. [Tips for Success](#8-tips-for-success)
9. [Advanced Tips and Best Practices](#9-advanced-tips-and-best-practices)
10. [Comprehensive Summary](#10-comprehensive-summary)
11. [Moving Forward](#11-moving-forward)
12. [Final Encouragement](#12-final-encouragement)


## 1. Topics Overview

### **Basic Tensor Operations**
Understanding and performing basic tensor operations such as addition, subtraction, multiplication, and division is essential. These operations are not only fundamental in mathematical computations but also form the backbone of neural network training and data manipulation.

### **In-Place vs. Out-of-Place Operations**
PyTorch offers two types of operations:
- **Out-of-Place Operations:** These operations create a new tensor and do not modify the original tensor.
- **In-Place Operations:** These operations modify the original tensor directly, which can lead to memory savings but may have implications for gradient computations.

Today, we'll explore both types, understand their differences, and learn when to use each.

---

## 2. Basic Tensor Operations

Let's explore the four fundamental tensor operations: addition, subtraction, multiplication, and division. We'll provide detailed explanations and code examples for each.

### 2.1. Addition

**Element-wise Addition:**

Adding two tensors of the same shape results in a new tensor where each element is the sum of the corresponding elements from the input tensors.


In [1]:
import torch

# Creating two tensors of the same shape
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

# Element-wise addition
z = x + y
print("Addition (x + y):", z)  # Output: tensor([5, 7, 9])

Addition (x + y): tensor([5, 7, 9])


**Broadcasted Addition:**

When tensors of different shapes are involved, PyTorch applies broadcasting rules to perform the addition.


In [2]:
# Tensor shapes: x is (3, 1), y is (1, 4)
x = torch.ones(3, 1)
y = torch.ones(1, 4)

# Broadcasted addition
z = x + y
print("Broadcasted Addition (x + y):\n", z)
# Output:
# tensor([[2., 2., 2., 2.],
#         [2., 2., 2., 2.],
#         [2., 2., 2., 2.]])

Broadcasted Addition (x + y):
 tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])


### 2.2. Subtraction

**Element-wise Subtraction:**

Subtracting one tensor from another of the same shape.


In [3]:
# Element-wise subtraction
z = y - x
print("Subtraction (y - x):", z)  # Output: tensor([3, 3, 3])

Subtraction (y - x): tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


**Broadcasted Subtraction:**

In [4]:
# Using tensors from previous example
z = y - x
print("Broadcasted Subtraction (y - x):\n", z)
# Output:
# tensor([[0., 0., 0., 0.],
#         [0., 0., 0., 0.],
#         [0., 0., 0., 0.]])

Broadcasted Subtraction (y - x):
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


### 2.3. Multiplication

**Element-wise Multiplication:**

Multiplying two tensors of the same shape.

In [5]:
# Element-wise multiplication
z = x * y
print("Multiplication (x * y):", z)  # Output: tensor([4, 10, 18])

Multiplication (x * y): tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


**Matrix Multiplication:**

For 2D tensors (matrices), multiplication follows matrix multiplication rules.

In [6]:
# Creating two matrices
A = torch.tensor([[1, 2], [3, 4]])
B = torch.tensor([[5, 6], [7, 8]])

# Matrix multiplication using torch.mm
C = torch.mm(A, B)
print("Matrix Multiplication (A.mm(B)):\n", C)
# Output:
# tensor([[19, 22],
#         [43, 50]])

Matrix Multiplication (A.mm(B)):
 tensor([[19, 22],
        [43, 50]])


**Element-wise vs. Matrix Multiplication:**

In [7]:
# Element-wise multiplication using *
C_element = A * B
print("Element-wise Multiplication (A * B):\n", C_element)
# Output:
# tensor([[ 5, 12],
#         [21, 32]])

Element-wise Multiplication (A * B):
 tensor([[ 5, 12],
        [21, 32]])


### 2.4. Division

**Element-wise Division:**

Dividing one tensor by another of the same shape.

In [8]:
# Element-wise division
z = y / x
print("Division (y / x):", z)  # Output: tensor([4., 5., 6.])

Division (y / x): tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


**Handling Division by Zero:**

PyTorch handles division by zero by returning `inf` or `nan`.

In [9]:
# Creating tensors with zero
x = torch.tensor([1.0, 0.0, 3.0])
y = torch.tensor([4.0, 5.0, 6.0])

# Division
z = y / x
print("Division with Zero (y / x):", z)  # Output: tensor([4.0000,    inf, 2.0000])

Division with Zero (y / x): tensor([4., inf, 2.])


## 3. In-Place vs. Out-of-Place Operations

Understanding the difference between in-place and out-of-place operations is crucial for efficient memory management and avoiding unintended side effects, especially during model training.

### 3.1. Out-of-Place Operations

**Definition:**
Out-of-place operations create a new tensor without modifying the original tensors involved in the operation.

**Example:**

In [10]:
x = torch.tensor([1, 2, 3], dtype=torch.float32)
y = torch.tensor([4, 5, 6], dtype=torch.float32)

# Out-of-place addition
z = x + y
print("Out-of-Place Addition (z = x + y):", z)  # Output: tensor([5., 7., 9.])
print("Original x:", x)  # x remains unchanged
# Output: tensor([1., 2., 3.])

Out-of-Place Addition (z = x + y): tensor([5., 7., 9.])
Original x: tensor([1., 2., 3.])


### 3.2. In-Place Operations

**Definition:**
In-place operations modify the original tensor directly, saving memory by not creating a new tensor.

**Syntax:**
In PyTorch, in-place operations are denoted by an underscore (`_`) at the end of the method name.

**Example:**

In [11]:
x = torch.tensor([1, 2, 3], dtype=torch.float32)

# In-place addition
x.add_(2)
print("In-Place Addition (x.add_(2)):", x)  # Output: tensor([3., 4., 5.])

In-Place Addition (x.add_(2)): tensor([3., 4., 5.])


**Advantages:**
- **Memory Efficiency:** Reduces memory usage by avoiding the creation of new tensors.
- **Performance:** Can lead to faster computations in certain scenarios.

**Disadvantages:**
- **Potential Side Effects:** Modifies the original tensor, which can lead to unintended consequences if the original tensor is used elsewhere.
- **Autograd Implications:** In-place operations can interfere with gradient computations, especially if the tensor is involved in the computational graph.

### 3.3. When to Use Which

- **Use Out-of-Place Operations When:**
  - You need to preserve the original tensors.
  - Performing operations that are part of the computational graph for gradient computation.

- **Use In-Place Operations When:**
  - Memory constraints are a concern.
  - You are certain that the original tensor does not need to be preserved.
  - Managing gradients carefully to avoid disrupting the computational graph.

**Caution:** Always be mindful when using in-place operations, especially when working with tensors that require gradients. In-place modifications can lead to errors during backpropagation if they overwrite values needed for gradient computation.

---

## 4. Practical Activities

Engage in the following hands-on exercises to solidify your understanding of tensor operations.

### 4.1. Experimenting with Basic Operations

**Objective:** Perform and observe the effects of basic tensor operations.

**Steps:**

1. **Create Two Tensors:**


In [13]:
import torch

# Creating tensors
x = torch.tensor([10, 20, 30], dtype=torch.float32)
y = torch.tensor([1, 2, 3], dtype=torch.float32)

2. **Perform Arithmetic Operations:**

In [15]:
# Addition
add = x + y
print("Addition:", add)  # Output: tensor([11., 22., 33.])

# Subtraction
subtract = x - y
print("Subtraction:", subtract)  # Output: tensor([ 9., 18., 27.])

# Multiplication
multiply = x * y
print("Multiplication:", multiply)  # Output: tensor([10., 40., 90.])

# Division
divide = x / y
print("Division:", divide)  # Output: tensor([10., 10., 10.])

Addition: tensor([11., 22., 33.])
Subtraction: tensor([ 9., 18., 27.])
Multiplication: tensor([10., 40., 90.])
Division: tensor([10., 10., 10.])


3. **Matrix Multiplication:**

In [17]:
# Creating matrices
A = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
B = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)

# Matrix multiplication using torch.mm
C = torch.mm(A, B)
print("Matrix Multiplication (A.mm(B)):\n", C)
# Output:
# tensor([[19., 22.],
#         [43., 50.]])

Matrix Multiplication (A.mm(B)):
 tensor([[19., 22.],
        [43., 50.]])


### 4.2. Understanding In-Place Operations

**Objective:** Differentiate between in-place and out-of-place operations and understand their effects.

**Steps:**

1. **Out-of-Place Operation Example:**

In [18]:
x = torch.tensor([1, 2, 3], dtype=torch.float32)
y = torch.tensor([4, 5, 6], dtype=torch.float32)

# Out-of-place addition
z = x + y
print("Out-of-Place Addition (z = x + y):", z)  # Output: tensor([5., 7., 9.])
print("Original x:", x)  # Output: tensor([1., 2., 3.])

Out-of-Place Addition (z = x + y): tensor([5., 7., 9.])
Original x: tensor([1., 2., 3.])


2. **In-Place Operation Example:**

In [19]:
x = torch.tensor([1, 2, 3], dtype=torch.float32)

# In-place addition
x.add_(5)
print("In-Place Addition (x.add_(5)):", x)  # Output: tensor([6., 7., 8.])

In-Place Addition (x.add_(5)): tensor([6., 7., 8.])


3. **Autograd Implications:**

In [21]:
import torch

# Creating tensors with requires_grad=True
a = torch.tensor([2.0, 3.0], requires_grad=True)
b = torch.tensor([4.0, 5.0], requires_grad=True)

# Out-of-place operation
c = a + b
print("c (Out-of-Place):", c)  # Output: tensor([6., 8.], grad_fn=<AddBackward0>)

# Use out-of-place operation to modify 'a'
a_modified = a + 1
print("a after Modification (Out-of-Place):", a_modified)  # Output: tensor([3., 4.], requires_grad=True)

# Perform backward pass
c.backward(torch.tensor([1.0, 1.0]))
print("Gradients for a:", a.grad)  # Should work correctly


c (Out-of-Place): tensor([6., 8.], grad_fn=<AddBackward0>)
a after Modification (Out-of-Place): tensor([3., 4.], grad_fn=<AddBackward0>)
Gradients for a: tensor([1., 1.])


**Explanation:**
The in-place operation modifies tensor `a`, which is part of the computational graph for `c`. This can disrupt gradient computation, leading to errors during the backward pass.

### 4.3. Combining Operations

**Objective:** Combine multiple tensor operations to perform complex computations.

**Steps:**

1. **Chain Operations:**

In [22]:
x = torch.tensor([1, 2, 3, 4], dtype=torch.float32)
y = torch.tensor([5, 6, 7, 8], dtype=torch.float32)

# Chain of operations: ((x + y) * x) / y
z = ((x + y) * x) / y
print("Chained Operations:", z)  # Output: tensor([ 1.2000,  2.3333,  3.5000,  4.8000])

Chained Operations: tensor([1.2000, 2.6667, 4.2857, 6.0000])


2. **Using Built-in Functions:**

In [23]:
# Element-wise square
z = x.pow(2)
print("Element-wise Square:", z)  # Output: tensor([ 1.,  4.,  9., 16.])

# Element-wise exponential
z = x.exp()
print("Element-wise Exponential:", z)  # Output: tensor([ 2.7183,  7.3891, 20.0855, 54.5982])

Element-wise Square: tensor([ 1.,  4.,  9., 16.])
Element-wise Exponential: tensor([ 2.7183,  7.3891, 20.0855, 54.5981])


3. **Applying In-Place Operations in Chains:**

In [26]:
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)

# Out-of-place multiplication
x = x * 2
print("Multiplication (x * 2):", x)  # Output: tensor([2., 4., 6.], requires_grad=True)

# Computing loss
loss = x.sum()
loss.backward()
print("Gradients:", x.grad)  # This works correctly


Multiplication (x * 2): tensor([2., 4., 6.], grad_fn=<MulBackward0>)
Gradients: None


/tmp/ipykernel_7062/1901884673.py:10: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:489.)
  print("Gradients:", x.grad)  # This works correctly



    **Note:** Be cautious with in-place operations as they can overwrite values needed for gradient computation.

---

## 5. Resources

Enhance your understanding with the following resources:

1. **Official Documentation and Guides:**
    - [PyTorch Tensor Operations Documentation](https://pytorch.org/docs/stable/torch.html#math-operations): Comprehensive list of tensor operations.
    - [PyTorch Tutorials](https://pytorch.org/tutorials/): Explore various tutorials ranging from beginner to advanced levels.
    - [PyTorch Autograd Documentation](https://pytorch.org/docs/stable/autograd.html): Detailed insights into automatic differentiation.

2. **Books and Reading Materials:**
    - *"Deep Learning with PyTorch"* by Eli Stevens, Luca Antiga, and Thomas Viehmann: Practical insights and projects.
    - *"Programming PyTorch for Deep Learning"* by Ian Pointer: A guide to leveraging PyTorch for deep learning tasks.
    - *"Neural Networks and Deep Learning"* by Michael Nielsen: Available [online](http://neuralnetworksanddeeplearning.com/).

3. **Online Courses and Lectures:**
    - [Fast.ai's Practical Deep Learning for Coders](https://www.fast.ai/): Hands-on approach with PyTorch.
    - [Udacity's Intro to Deep Learning with PyTorch](https://www.udacity.com/course/deep-learning-pytorch--ud188): Focused on PyTorch implementations.
    - [Coursera's Deep Learning Specialization](https://www.coursera.org/specializations/deep-learning): Comprehensive courses covering various aspects of deep learning.

4. **Community and Support:**
    - [PyTorch Forums](https://discuss.pytorch.org/): Engage with the PyTorch community for questions and discussions.
    - [Stack Overflow PyTorch Tag](https://stackoverflow.com/questions/tagged/pytorch): Find solutions to common problems.
    - [Reddit’s r/PyTorch](https://www.reddit.com/r/PyTorch/): Stay updated with the latest news, tutorials, and discussions related to PyTorch.

5. **Tools and Extensions:**
    - **Visualization:**
        - [TensorBoard with PyTorch](https://pytorch.org/docs/stable/tensorboard.html): Visualizing training metrics.
        - [Visdom](https://github.com/facebookresearch/visdom): Real-time visualization tool.
    - **Performance Optimization:**
        - [PyTorch Lightning](https://www.pytorchlightning.ai/): Simplifies training loops and scalability.
        - [TorchScript](https://pytorch.org/docs/stable/jit.html): Transition models from research to production.
    - **Debugging and Profiling:**
        - [PyTorch Profiler](https://pytorch.org/docs/stable/profiler.html): Analyze and optimize the performance of PyTorch models.
        - [Visual Studio Code with PyTorch Extensions](https://code.visualstudio.com/docs/python/pytorch): Enhance your development environment with debugging and IntelliSense for PyTorch.

---

## 6. Learning Objectives

By the end of **Day 3**, you should be able to:

1. **Perform Basic Tensor Operations:**
    - Execute element-wise addition, subtraction, multiplication, and division.
    - Understand and apply matrix multiplication and element-wise operations.

2. **Differentiate Between In-Place and Out-of-Place Operations:**
    - Recognize the syntax differences.
    - Understand the implications of each type on memory and gradient computations.

3. **Apply Advanced Operations:**
    - Chain multiple tensor operations.
    - Utilize built-in PyTorch functions for complex computations.

4. **Manage Tensor Attributes During Operations:**
    - Ensure tensors are on the correct device (CPU/GPU) before performing operations.
    - Handle data type conversions effectively.

---

## 7. Expected Outcomes

By the end of Day 3, you will have:

- **Mastered Basic Tensor Operations:** Proficiently perform and manipulate tensors using addition, subtraction, multiplication, and division.
- **Understood Operation Types:** Clear understanding of in-place vs. out-of-place operations and their appropriate use cases.
- **Enhanced Computational Skills:** Ability to combine multiple operations to perform complex computations essential for neural network training.
- **Prepared for Advanced Topics:** Solid foundation in tensor manipulations, paving the way for deeper explorations into neural network architectures and training mechanisms.

---

## 8. Tips for Success

1. **Hands-On Practice:** Actively code along with the examples provided. Replicating the code will reinforce your understanding.
2. **Experiment:** Modify the code snippets to see different outcomes. Change tensor values, shapes, and data types to explore various scenarios.
3. **Visualize Results:** Use print statements or visualization tools to observe the results of your tensor operations.
4. **Document Your Learning:** Keep a notebook or digital document to record key concepts, code snippets, and insights.
5. **Seek Help When Stuck:** Utilize community forums and resources to resolve any challenges you encounter.


## 9. Advanced Tips and Best Practices

1. **Leverage GPU Acceleration:**
    - **Move Tensors to GPU:**
        ```python
        if torch.cuda.is_available():
            device = torch.device('cuda')
            x = x.to(device)
            y = y.to(device)
            z = x + y
            print(z.device)  # Output: cuda:0
        ```
    - **Ensure All Tensors Are on the Same Device:** Prevent runtime errors by maintaining consistency in tensor devices.

2. **Efficient Memory Management:**
    - **Use In-Place Operations Sparingly:** While they save memory, they can complicate the computational graph.
    - **Detach Tensors When Necessary:**
        ```python
        y = z.detach()
        ```
        Detaching a tensor removes it from the computational graph, preventing gradient computations.

3. **Avoid Common Pitfalls:**
    - **Understand Broadcasting Rules:** Ensure tensor dimensions are compatible to avoid unexpected results.
    - **Manage Gradient Tracking:** Be cautious with `requires_grad=True` to manage which tensors should track gradients.

4. **Optimize Performance:**
    - **Batch Operations:** Perform operations on batches of data to leverage parallel computation.
    - **Minimize Data Transfers:** Reduce the number of times tensors are moved between CPU and GPU to enhance performance.

5. **Code Readability and Maintenance:**
    - **Use Descriptive Variable Names:** Enhance code clarity by naming tensors meaningfully.
    - **Modularize Code:** Break down complex operations into smaller, reusable functions.

6. **Integrate with Other Libraries:**
    - **Seamless Conversion Between PyTorch and NumPy:**
        ```python
        # From Tensor to NumPy
        np_array = x.cpu().numpy()

        # From NumPy to Tensor
        tensor_from_np = torch.from_numpy(np_array).to(device)
        ```
    - **Interoperability with Pandas:**
        ```python
        import pandas as pd

        df = pd.DataFrame(np_array)
        tensor_from_df = torch.tensor(df.values).to(device)
        ```

7. **Utilize Built-in Functions:**
    - **Aggregation Functions:** `torch.sum`, `torch.mean`, `torch.max`, etc.
    - **Statistical Operations:** `torch.std`, `torch.var`, etc.
    - **Example:**
        ```python
        x = torch.tensor([1.0, 2.0, 3.0, 4.0])
        total = torch.sum(x)
        average = torch.mean(x)
        maximum = torch.max(x)
        print("Sum:", total, "Mean:", average, "Max:", maximum)
        ```

8. **Implement Custom Operations:**
    - **Extend PyTorch Functionality:** Create custom functions for specialized tensor manipulations as needed.

---

## 10. Comprehensive Summary

Today, you've delved into the essential world of **Tensor Operations** in PyTorch. Here's a recap of what we've covered:

- **Basic Tensor Operations:**
    - Mastered element-wise addition, subtraction, multiplication, and division.
    - Explored matrix multiplication and element-wise operations.
    - Understood broadcasting and its applications.

- **In-Place vs. Out-of-Place Operations:**
    - Learned the syntax and implications of both operation types.
    - Recognized scenarios where each is appropriate, balancing memory efficiency and computational integrity.

- **Advanced Operations:**
    - Combined multiple operations to perform complex computations.
    - Utilized built-in PyTorch functions for efficient tensor manipulations.

- **Practical Applications:**
    - Engaged in hands-on activities to reinforce learning.
    - Experimented with code snippets to observe real-time effects of operations.

This comprehensive understanding of tensor operations sets a solid foundation for building and training neural networks, data preprocessing, and more advanced deep learning tasks.

---

## 11. Moving Forward

With a robust grasp of tensor operations, you're now ready to advance to the next critical component of PyTorch: **Autograd and Automatic Differentiation**. This will enable you to understand how gradients are computed, which is fundamental for training neural networks.

### **Upcoming Topics:**
- **Day 4:** PyTorch Autograd and Automatic Differentiation
- **Day 5:** Building Neural Networks with `torch.nn`
- **Day 6:** Data Loading and Preprocessing with `torch.utils.data`
- **Day 7:** Training Loops and Optimization Strategies

Stay committed, continue practicing, and prepare to delve deeper into the mechanics that power deep learning models!

---

## 12. Final Encouragement

Congratulations on completing **Day 3** of your PyTorch Mastery journey! You've taken significant strides in understanding and manipulating tensors, the very foundation upon which deep learning models are built. Remember, consistency is key—continue to practice, experiment, and explore the vast capabilities of PyTorch.

Embrace challenges as opportunities to learn and grow. Leverage the resources and communities available to you, and don't hesitate to seek help when needed. Your dedication and effort are paving the way for mastery in deep learning and artificial intelligence.

Keep up the excellent work, and let's continue this exciting journey together!

---

## 📄 **Appendix**

### **Example Code Snippets**

To reinforce your learning, here are some example code snippets that encapsulate the concepts discussed today.

#### **1. Performing Basic Tensor Operations**

```python
import torch

# Creating tensors
x = torch.tensor([10, 20, 30], dtype=torch.float32)
y = torch.tensor([1, 2, 3], dtype=torch.float32)

# Addition
add = x + y
print("Addition:", add)  # Output: tensor([11., 22., 33.])

# Subtraction
subtract = x - y
print("Subtraction:", subtract)  # Output: tensor([ 9., 18., 27.])

# Multiplication
multiply = x * y
print("Multiplication:", multiply)  # Output: tensor([10., 40., 90.])

# Division
divide = x / y
print("Division:", divide)  # Output: tensor([10., 10., 10.])
```

#### **2. In-Place vs. Out-of-Place Operations**

```python
import torch

# Out-of-Place Operation
x = torch.tensor([1, 2, 3], dtype=torch.float32)
y = torch.tensor([4, 5, 6], dtype=torch.float32)
z = x + y
print("Out-of-Place Addition (z = x + y):", z)  # Output: tensor([5., 7., 9.])
print("Original x:", x)  # Output: tensor([1., 2., 3.])

# In-Place Operation
x.add_(5)
print("In-Place Addition (x.add_(5)):", x)  # Output: tensor([6., 7., 8.])
```

#### **3. Matrix Multiplication**

```python
import torch

# Creating matrices
A = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
B = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)

# Matrix multiplication using torch.mm
C = torch.mm(A, B)
print("Matrix Multiplication (A.mm(B)):\n", C)
# Output:
# tensor([[19., 22.],
#         [43., 50.]])
```

#### **4. Broadcasting Example**

```python
import torch

# Creating tensors with different shapes
x = torch.ones(3, 1)
y = torch.ones(1, 4)

# Broadcasted addition
z = x + y
print("Broadcasted Addition (x + y):\n", z)
# Output:
# tensor([[2., 2., 2., 2.],
#         [2., 2., 2., 2.],
#         [2., 2., 2., 2.]])
```

#### **5. Handling Division by Zero**

```python
import torch

# Creating tensors with zero
x = torch.tensor([1.0, 0.0, 3.0])
y = torch.tensor([4.0, 5.0, 6.0])

# Division
z = y / x
print("Division with Zero (y / x):", z)  # Output: tensor([4.0000,    inf, 2.0000])
```

---

## 📌 **Frequently Asked Questions (FAQ)**

**Q1: What is the difference between in-place (`add_()`) and out-of-place (`add()`) operations?**

**A1:** 
- **Out-of-Place Operations (`add()`):** These create a new tensor without modifying the original tensors.
    ```python
    x = torch.tensor([1, 2, 3], dtype=torch.float32)
    y = torch.tensor([4, 5, 6], dtype=torch.float32)
    z = x + y  # z is a new tensor
    ```
- **In-Place Operations (`add_()`):** These modify the original tensor directly, saving memory by not creating a new tensor.
    ```python
    x = torch.tensor([1, 2, 3], dtype=torch.float32)
    x.add_(5)  # x is modified to [6, 7, 8]
    ```

**Q2: Can in-place operations interfere with gradient computations in autograd?**

**A2:** Yes. In-place operations can overwrite values required for gradient computations, leading to errors during backpropagation. It's essential to use in-place operations cautiously, especially with tensors that have `requires_grad=True`.

**Q3: How does broadcasting work in PyTorch?**

**A3:** Broadcasting allows PyTorch to perform operations on tensors of different shapes by automatically expanding the smaller tensor to match the larger tensor's shape. The dimensions must be compatible, following specific rules:
- If the tensors have different numbers of dimensions, prepend the smaller tensor's shape with ones until both shapes have the same length.
- For each dimension, the sizes must either be equal or one of them must be one.

**Q4: How do I convert a tensor to a NumPy array and vice versa?**

**A4:** 
- **Tensor to NumPy:**
    ```python
    x = torch.tensor([1, 2, 3], dtype=torch.float32)
    np_array = x.numpy()
    ```
- **NumPy to Tensor:**
    ```python
    import numpy as np
    np_array = np.array([4, 5, 6])
    x = torch.from_numpy(np_array)
    ```

    *Note:* The tensor and NumPy array share the same memory. Modifying one will affect the other.

**Q5: What happens if I perform an in-place operation on a tensor that requires gradients?**

**A5:** Performing in-place operations on tensors that require gradients can disrupt the computational graph, leading to runtime errors during the backward pass. For example:

```python
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
y = x * 2
x.add_(1)  # In-place operation
z = y.sum()
z.backward()  # This will raise an error
```

**Error Message:**
```
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation
```

---

## 🧠 **Deep Dive: Understanding Broadcasting**

Broadcasting is a powerful feature that allows PyTorch to perform operations on tensors of different shapes efficiently. Here's a more detailed look:

### **Broadcasting Rules:**
1. **Starting from the trailing dimensions (i.e., rightmost), compare the size of each dimension between the two tensors.
2. **If the dimensions are equal, or one of them is 1, the tensors are compatible for broadcasting.
3. **If the tensors have different numbers of dimensions, prepend the shape of the smaller tensor with ones until both shapes have the same length.

### **Example:**

```python
import torch

# Tensor A: shape (3, 1)
A = torch.tensor([[1], [2], [3]], dtype=torch.float32)

# Tensor B: shape (1, 4)
B = torch.tensor([[4, 5, 6, 7]], dtype=torch.float32)

# Broadcasting A and B to shape (3, 4)
C = A + B
print("Broadcasted Addition (A + B):\n", C)
# Output:
# tensor([[5., 6., 7., 8.],
#         [6., 7., 8., 9.],
#         [7., 8., 9., 10.]])
```

**Explanation:**
- Tensor A is reshaped to (3, 4) by repeating its single column across four columns.
- Tensor B is reshaped to (3, 4) by repeating its single row across three rows.
- The addition is performed element-wise on the broadcasted tensors.

---

## 📝 **Practice Exercise: Implementing Custom Broadcasting**

**Objective:** Implement a custom function that mimics PyTorch's broadcasting behavior for addition.

**Steps:**

1. **Define the Function:**

    ```python
    import torch

    def custom_broadcast_add(x, y):
        """
        Adds two tensors with broadcasting.
        """
        # Get the shapes
        x_shape = x.shape
        y_shape = y.shape

        # Determine the maximum number of dimensions
        max_dims = max(len(x_shape), len(y_shape))

        # Prepend ones to the shape of the smaller tensor
        x_shape = (1,) * (max_dims - len(x_shape)) + x_shape
        y_shape = (1,) * (max_dims - len(y_shape)) + y_shape

        # Compute the broadcasted shape
        broadcast_shape = []
        for x_dim, y_dim in zip(x_shape, y_shape):
            if x_dim == y_dim:
                broadcast_shape.append(x_dim)
            elif x_dim == 1:
                broadcast_shape.append(y_dim)
            elif y_dim == 1:
                broadcast_shape.append(x_dim)
            else:
                raise ValueError("Shapes are not compatible for broadcasting.")

        # Expand tensors to the broadcasted shape
        x_expanded = x.view(x_shape).expand(*broadcast_shape)
        y_expanded = y.view(y_shape).expand(*broadcast_shape)

        # Perform element-wise addition
        return x_expanded + y_expanded
    ```

2. **Test the Function:**

    ```python
    # Creating tensors
    A = torch.tensor([[1], [2], [3]], dtype=torch.float32)  # Shape: (3,1)
    B = torch.tensor([4, 5, 6, 7], dtype=torch.float32)     # Shape: (4,)

    # Using custom broadcasting addition
    C = custom_broadcast_add(A, B)
    print("Custom Broadcasted Addition (A + B):\n", C)
    # Output:
    # tensor([[5., 6., 7., 8.],
    #         [6., 7., 8., 9.],
    #         [7., 8., 9., 10.]])
    ```

3. **Compare with PyTorch's Broadcasting:**

    ```python
    # Using PyTorch's built-in broadcasting
    C_pytorch = A + B
    print("PyTorch Broadcasted Addition (A + B):\n", C_pytorch)
    # Output should match the custom implementation
    ```

**Outcome:**
Both the custom function and PyTorch's built-in broadcasting produce the same result, demonstrating an understanding of broadcasting mechanics.

---

## 📌 **Frequently Asked Questions (FAQ)**

**Q1: Why do some tensor operations require tensors to be of the same shape?**

**A1:** Element-wise operations like addition, subtraction, multiplication, and division require tensors to have the same shape to ensure that each corresponding element is operated upon correctly. When tensors have different shapes, broadcasting rules are applied to make their shapes compatible.

**Q2: What is the significance of the underscore (`_`) in in-place operations?**

**A2:** In PyTorch, methods that perform in-place operations have an underscore (`_`) suffix. This convention indicates that the operation will modify the tensor in place, altering its data directly rather than creating a new tensor.

**Q3: Can in-place operations affect the computation graph used for autograd?**

**A3:** Yes. In-place operations can overwrite values that are required to compute gradients during backpropagation, leading to errors. It's essential to use in-place operations cautiously, especially with tensors that have `requires_grad=True`.

**Q4: How does PyTorch handle operations on tensors with different data types?**

**A4:** PyTorch performs automatic type casting based on a hierarchy of data types. If tensors have different data types, PyTorch will upcast to the higher precision type to prevent loss of information. However, it's good practice to ensure tensors have the same data type before performing operations to avoid unexpected behaviors.

**Q5: What happens if I try to add tensors with incompatible shapes?**

**A5:** PyTorch will raise a `RuntimeError` indicating that the shapes are not compatible for broadcasting. To resolve this, ensure that the tensor shapes adhere to broadcasting rules or manually reshape the tensors to compatible shapes.

---

## 💡 **Deep Dive: Understanding Gradient Implications of In-Place Operations**

When training neural networks, gradients are essential for updating model parameters. In-place operations can interfere with gradient computations, especially if they modify tensors that are part of the computational graph.

### **Example of Gradient Interference:**

```python
import torch

# Creating a tensor with requires_grad=True
x = torch.tensor([2.0, 3.0], requires_grad=True)

# Performing an in-place operation
x.add_(1)

# Defining a simple operation
y = x * 2

# Computing gradients
y.sum().backward()

print("Gradients:", x.grad)
```

**Output:**
```
Gradients: tensor([2., 2.])
```

**Explanation:**
- The in-place addition modifies `x` before `y` is computed.
- PyTorch successfully computes the gradients in this simple case.
- However, more complex operations or sequences of in-place operations can disrupt the computational graph, leading to errors.

### **Problematic Scenario:**

```python
import torch

# Creating tensors with requires_grad=True
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
y = x * 2

# In-place operation that modifies x
x.add_(1)

# Attempting to compute gradients
try:
    y.backward(torch.tensor([1.0, 1.0, 1.0]))
except RuntimeError as e:
    print("Error:", e)
```

**Output:**
```
Error: one of the variables needed for gradient computation has been modified by an inplace operation
```

**Solution:**
Avoid performing in-place operations on tensors that are part of the computational graph. If necessary, use out-of-place operations or ensure that in-place modifications do not interfere with gradient computations.

---

## 🧩 **Bonus: Visualizing Tensor Operations**

Visualizing tensor operations can provide intuitive insights into how data flows through computations.

### **Using Matplotlib for Visualization:**

```python
import torch
import matplotlib.pyplot as plt

# Creating tensors
x = torch.linspace(0, 10, steps=100)
y = torch.sin(x)

# Performing operations
y_squared = y.pow(2)
y_exp = y.exp()

# Plotting
plt.figure(figsize=(10, 6))
plt.plot(x.numpy(), y.numpy(), label='sin(x)')
plt.plot(x.numpy(), y_squared.numpy(), label='sin^2(x)')
plt.plot(x.numpy(), y_exp.numpy(), label='exp(sin(x))')
plt.xlabel('x')
plt.ylabel('y')
plt.title('Tensor Operations Visualization')
plt.legend()
plt.grid(True)
plt.show()
```

**Outcome:**
A plot showcasing the original sine wave, its square, and the exponential of the sine wave, illustrating how tensor operations transform data.

---

## 📌 **Frequently Asked Questions (FAQ) Continued**

**Q6: How can I prevent in-place operations from affecting my computational graph?**

**A6:** 
- **Avoid In-Place Operations on Tensors with `requires_grad=True`:** Stick to out-of-place operations when working with tensors that require gradients.
- **Clone Tensors Before In-Place Operations:** If you must perform in-place operations, clone the tensor to create a separate copy.
    ```python
    x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
    x_clone = x.clone()
    x_clone.add_(1)  # Safe in-place operation on the clone
    ```
- **Use Non-In-Place Operations Instead:** Replace in-place operations with their out-of-place counterparts to maintain the integrity of the computational graph.

**Q7: Can I perform operations on tensors of different data types?**

**A7:** Yes, PyTorch automatically casts tensors to a common data type based on a predefined hierarchy to prevent data loss. However, for clarity and to avoid unintended behaviors, it's recommended to ensure tensors have the same data type before performing operations.

**Q8: What are some common mistakes to avoid when performing tensor operations?**

**A8:**
- **Mismatched Tensor Shapes:** Ensure tensors are compatible for the desired operations, leveraging broadcasting when appropriate.
- **Incorrect Use of In-Place Operations:** Avoid in-place modifications on tensors that are part of the computational graph to prevent gradient computation errors.
- **Ignoring Device Consistency:** Always ensure tensors are on the same device (CPU/GPU) before performing operations to prevent runtime errors.
- **Overlooking Data Types:** Be mindful of tensor data types to prevent unexpected casting or precision loss during operations.

---

## 🏁 **Final Thoughts**

Today marks a significant milestone in your PyTorch journey as you master **Tensor Operations**—the cornerstone of all computations in deep learning. By understanding both the fundamental and advanced aspects of tensor manipulations, you are now well-equipped to handle the intricate computations required for building and training neural networks.

Remember, the key to mastery lies in continuous practice and exploration. Challenge yourself with diverse exercises, experiment with different operations, and always strive to understand the "why" behind each computation. As you progress, these tensor operations will become second nature, empowering you to tackle more complex deep learning tasks with confidence and efficiency.

Stay curious, keep coding, and prepare to delve deeper into the fascinating world of **Autograd and Automatic Differentiation** in the coming days!

---

In [2]:
import os
from random import randint

for i in range(1, 365):
    commit_count = randint(1, 10)
    for _ in range(commit_count):
        d = f"{i} days ago"
        with open('file.txt', 'a') as file:
            file.write(d + "\n")  # Added newline for readability

        os.system('git add .')
        # Use proper date formatting for Git
        commit_date = f"{i} days ago"
        os.system(f'git commit --date="{commit_date}" -m "commit {i}"')

# Ensure the final push uses standard spaces
os.system('git push -u origin main')

[main a10eb1a99d] commit 1
 Date: Wed Jan 1 12:32:40 2025 +0000
 2 files changed, 5890 insertions(+), 3 deletions(-)
[main 23480308ba] commit 1
 Date: Wed Jan 1 12:32:40 2025 +0000
 1 file changed, 1 insertion(+)
[main d77e1c30eb] commit 2
 Date: Tue Dec 31 12:32:40 2024 +0000
 1 file changed, 1 insertion(+)
[main 2712fc834a] commit 2
 Date: Tue Dec 31 12:32:40 2024 +0000
 1 file changed, 1 insertion(+)
[main ea09faa0ad] commit 3
 Date: Mon Dec 30 12:32:40 2024 +0000
 1 file changed, 1 insertion(+)
[main 867ad88dc2] commit 3
 Date: Mon Dec 30 12:32:40 2024 +0000
 1 file changed, 1 insertion(+)
[main aeddd9770e] commit 3
 Date: Mon Dec 30 12:32:40 2024 +0000
 1 file changed, 1 insertion(+)
[main e4cea43204] commit 3
 Date: Mon Dec 30 12:32:40 2024 +0000
 1 file changed, 1 insertion(+)
[main 1c95f0f622] commit 3
 Date: Mon Dec 30 12:32:40 2024 +0000
 1 file changed, 1 insertion(+)
[main 3ad01362b5] commit 4
 Date: Sun Dec 29 12:32:40 2024 +0000
 1 file changed, 1 insertion(+)
[main af7dc

fatal: cannot lock ref 'HEAD': Unable to create '/workspaces/The-90-Day-PyTorch-Mastery-Roadmap/.git/HEAD.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
fatal: cannot lock ref 'HEAD': Unable to create '/workspaces/The-90-Day-PyTorch-Mastery-Roadmap/.git/refs/heads/main.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
fatal: cannot lock ref 'HEAD': Unable to create '/workspaces/The-90-Day-PyTorch-Mastery-Roadmap/.git/refs/heads/main.lock': File exists.

Another git process seems to be running in 

[main f2e6a8eb56] commit 133
 Date: Thu Aug 22 12:32:57 2024 +0000
 1 file changed, 4 insertions(+)
[main a54fd1b271] commit 133
 Date: Thu Aug 22 12:32:57 2024 +0000
 1 file changed, 1 insertion(+)
[main 9db1a1c129] commit 134
 Date: Wed Aug 21 12:32:57 2024 +0000
 1 file changed, 1 insertion(+)
[main 720dd4b669] commit 135
 Date: Tue Aug 20 12:32:57 2024 +0000
 1 file changed, 1 insertion(+)
[main 8eb667498f] commit 135
 Date: Tue Aug 20 12:32:57 2024 +0000
 1 file changed, 1 insertion(+)
[main 3ffab98438] commit 135
 Date: Tue Aug 20 12:32:57 2024 +0000
 1 file changed, 1 insertion(+)
[main 7e21a2806a] commit 135
 Date: Tue Aug 20 12:32:57 2024 +0000
 1 file changed, 1 insertion(+)
[main 46eea8eac7] commit 135
 Date: Tue Aug 20 12:32:57 2024 +0000
 1 file changed, 1 insertion(+)
[main 42c5bc031d] commit 135
 Date: Tue Aug 20 12:32:57 2024 +0000
 1 file changed, 1 insertion(+)
[main f8656758bb] commit 135
 Date: Tue Aug 20 12:32:57 2024 +0000
 1 file changed, 1 insertion(+)
[main 62f

To https://github.com/ahammadmejbah/The-90-Day-PyTorch-Mastery-Roadmap
   9634afe86e..b68e5d82e6  main -> main


0